import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/Sidebar";
import Script from "next/script";
import { Settings, Users, Map } from "lucide-react";
import BottomNav from "@/components/bottom-nav";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <Script
        defer
        src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyB-AXLL_gGcVybSe8GfBBG3oOuWVgHosjc&libraries=places`}
      />
      <NextIntlClientProvider>
        <body className="flex flex-row text-gray-900">
          <div className="hidden md:block">
            <Sidebar />
          </div>
          <div className="flex flex-col w-full h-screen">
            <main className="flex-1 min-h-0 overflow-hidden">{children}</main>
            <div className="md:hidden">
              <BottomNav />
            </div>
          </div>
          <Toaster />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
