import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import "./globals.css";
import { Sidebar } from "@/components/sidebar";
import Script from "next/script";
import BottomNav from "@/components/bottom-nav";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navigationLinks = [
  { href: "/", label: "Map", icon: "map" },
  { href: "/clients", label: "Clients", icon: "users" },
  { href: "/settings", label: "Settings", icon: "settings" },
];

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <Script
        defer
        src={`https://maps.googleapis.com/maps/api/js?key=${process.env.GOOGLE_MAPS_API_KEY}&libraries=places`}
      />
      <NextIntlClientProvider>
        <body className="flex flex-row text-gray-900">
          <div className="hidden md:block">
            <Sidebar section={navigationLinks} />
          </div>
          <div className="flex flex-col w-full h-screen">
            <main className="flex-1 min-h-0 overflow-hidden">{children}</main>
            <div className="md:hidden">
              <BottomNav section={navigationLinks} />
            </div>
          </div>
          <Toaster />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
